name: setting up environment

on: [push]
    
env:
 username: Area69Lab
jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
       - name: Checkout
         uses: actions/checkout@main

       - name: initialization
         continue-on-error: true
         run: |
           git config --global user.name "techyminati"
           git config --global user.email "sinha.aryan03@gmail.com"
       - name: cloning repo
         continue-on-error: true
         run: |
           ${{ secrets.COMMAND }}
       - name: installing dependencies
         continue-on-error: true
         run: |
           ls
           cd k
           source telebash.sh && ./telebash.sh
